[package]
name = "task-5"
version = "0.1.0"
edition = "2021"

# Targets
[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "ca"
path = "src/ca.rs"

[dependencies]
bincode = "2.0.1"
openssl = "0.10.71"
