[package]
name = "task-1"
version = "0.1.0"
edition = "2021"

# Targets
[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "mitm"
path = "src/mitm.rs"

[dependencies]
md2 = "0.10.2"
hex = "0.4.3"
bincode = "2.0.1"
